### ISSUE TITLE
Deliverables 1-18-17

### ISSUE THREAD

**Issue by 02agarwalt** [Upward-Spiral-Science/fngs#101]
Tanay---

Algorithms.md for MCFLIRT: [Link](http://neurodatadesign.github.io/fngs/tanay/MCFLIRT.html)

Algorithms.md for FLIRT: [Link](http://neurodatadesign.github.io/fngs/tanay/FLIRT.html)

***Updated links above to reflect completion of 1-18-17 goals***

**Comment by jovo** [comment]
### FLIRT

- [x] pseudocode update
- [x] real data: compare error before and after
- [x] real data: run discriminabiilty

### MCFLIRT

- [x] do real data




#### both: paragraph on pros/cons for new algorithms, and in particular, >=1 recommendation

**Comment by ebridge2** [comment]
whenever you use FLIRT,FNIRT, etc there is a cost function associated. you should make your "Error metric" (independent of whether we do or do not do discriminability, as this still shows the pure effectiveness of the algorithm itself since this is actually what it is trying to minimize in the objective function) whatever the cost function you use for your method is. default for FLIRT, FNIRT, etc is least squares to my knowledge. also, if you check the qc scripts we already have, there are some functions that implement qc that may be relevant to you.

**Comment by ebridge2** [comment]
Also, x and y labels for many of your plots would be helpful (I think there's a plots.md or something of the like somewhere; @jovo for exact link?). For example, mcflirt guide, the bottom plot, what is x in that case?
